// 15 Angular/src/app/components/description/description.component.ts
import { Component, Input, OnInit, } from '@angular/core';
import { Serv1Service } from 'src/app/services/serv1.service';
import { IDrinks } from '../card/card.component';

@Component({
  selector: 'app-description',
  templateUrl: './description.component.html',
  styleUrls: ['./description.component.less']
})
export class DescriptionComponent implements OnInit {

  @Input() descr!: IDrinks[];
  @Input() isShowDesc!: boolean;
  @Input() idSwitch!: number;

  
  constructor(private serveService: Serv1Service) { 
    this.isShowDesc = true;
  }

  ngOnInit(): void {
    this.serveService.bType$.subscribe((bType) => this.log(bType)); 
  }
  
  private log(data: boolean): void {   
    this.isShowDesc = data;
  }

  public handlerClick() {
    this.serveService.bType$.next(!this.isShowDesc); 
  }
}


<div class="background"></div>
<div class="wrapper">
    <div class="description">
        <div class="close"><input type="button" value="X" (click)="handlerClick()"></div>
        <div class="desc_inner">
            <div class="desc_image">
                <img [src]="descr[idSwitch].strDrinkThumb" alt="drink">
                <h2>{{descr[idSwitch].strDrink}}</h2>
            </div>
            <div class="desc_body">
                <h3>How to make:</h3>
                <p>{{descr[idSwitch].strInstructions}}</p>
                <hr>
                <div class="innerFlex">
                    <div class="ingredients">
                        <h3>Ingredients:</h3>
                        <ul>
                            <li>{{descr[idSwitch].strIngredient1}}</li>
                            <li>{{descr[idSwitch].strIngredient2}}</li>
                            <li>{{descr[idSwitch].strIngredient3}}</li>
                            <li>{{descr[idSwitch].strIngredient4}}</li>
                            <li>{{descr[idSwitch].strIngredient5}}</li>
                            <li>{{descr[idSwitch].strIngredient6}}</li>
                            <li>{{descr[idSwitch].strIngredient7}}</li>
                        </ul>
                    </div>
                    <div class="measures">
                        <h3>Measures:</h3>
                        <ul>
                            <li>{{descr[idSwitch].strMeasure1}}</li>
                            <li>{{descr[idSwitch].strMeasure2}}</li>
                            <li>{{descr[idSwitch].strMeasure3}}</li>
                            <li>{{descr[idSwitch].strMeasure4}}</li>
                            <li>{{descr[idSwitch].strMeasure5}}</li>
                            <li>{{descr[idSwitch].strMeasure6}}</li>
                            <li>{{descr[idSwitch].strMeasure7}}</li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

// 17 React/src/components/drink/description/description.jsx
import { useState } from "react";
import "./style.css";

export function Desc({ data, id }) {

    function handleClick() {
        let inner = document.querySelector('.inner');
        inner.style.display = 'none';  
    }
    
    return (
        <div className="inner">
            <div className="background"></div>
            <div className="wrapper">
                <div className="description">
                    <div className="close"><input type="button" value="X" onClick={handleClick}/></div>
                    <div className="desc_inner">
                        <div className="desc_image">
                            <img src={data[id].strDrinkThumb} alt="drink" />
                            <h2>{data[id].strDrink}</h2>
                        </div>
                        <div className="desc_body">
                            <h3>How to make:</h3>
                            <p>{data[id].strInstructions}</p>
                            <hr/>
                            <div className="innerFlex">
                                <div className="ingredients">
                                    <h3>Ingredients:</h3>
                                    <ul>
                                        <li>{data[id].strIngredient1}</li>
                                        <li>{data[id].strIngredient2}</li>
                                        <li>{data[id].strIngredient3}</li>
                                        <li>{data[id].strIngredient4}</li>
                                        <li>{data[id].strIngredient5}</li>
                                        <li>{data[id].strIngredient6}</li>
                                        <li>{data[id].strIngredient7}</li>
                                    </ul>
                                </div>
                                <div className="measures">
                                    <h3>Measures:</h3>
                                    <ul>
                                        <li>{data[id].strMeasure1}</li>
                                        <li>{data[id].strMeasure2}</li>
                                        <li>{data[id].strMeasure3}</li>
                                        <li>{data[id].strMeasure4}</li>
                                        <li>{data[id].strMeasure5}</li>
                                        <li>{data[id].strMeasure6}</li>
                                        <li>{data[id].strMeasure7}</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    );
}
